version: '3'
services:
  alpine-container:
    container_name: alpinevim
    build:
      context: .
      dockerfile: Dockerfile
    image: brunojoao3/alpine-custom:alpinevim
    volumes:
      - alpine-data:/app
    tty: true
volumes:
  alpine-data:
